// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EEnKBN-6r6qDk8rucn0clqlXSd0f2e0',
    appId: '1:366517592732:web:5245857b721fffa6da4359',
    messagingSenderId: '366517592732',
    projectId: 'chattingapp-a7aef',
    authDomain: 'chattingapp-a7aef.firebaseapp.com',
    storageBucket: 'chattingapp-a7aef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsey0an4xPdr1yvlyX_tpDuhowwbp4xHY',
    appId: '1:366517592732:android:bf37f9b09b3d2bc1da4359',
    messagingSenderId: '366517592732',
    projectId: 'chattingapp-a7aef',
    storageBucket: 'chattingapp-a7aef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL5XQjm_PTZV9KgSVZsLhiDtYZmQ5dsVI',
    appId: '1:366517592732:ios:768f97160b9e8aa2da4359',
    messagingSenderId: '366517592732',
    projectId: 'chattingapp-a7aef',
    storageBucket: 'chattingapp-a7aef.appspot.com',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL5XQjm_PTZV9KgSVZsLhiDtYZmQ5dsVI',
    appId: '1:366517592732:ios:768f97160b9e8aa2da4359',
    messagingSenderId: '366517592732',
    projectId: 'chattingapp-a7aef',
    storageBucket: 'chattingapp-a7aef.appspot.com',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9EEnKBN-6r6qDk8rucn0clqlXSd0f2e0',
    appId: '1:366517592732:web:ffd4263689a77a41da4359',
    messagingSenderId: '366517592732',
    projectId: 'chattingapp-a7aef',
    authDomain: 'chattingapp-a7aef.firebaseapp.com',
    storageBucket: 'chattingapp-a7aef.appspot.com',
  );
}
